<template>
    <main>
      <section>
        <Book-Comp></Book-Comp>
        <Book-Comp></Book-Comp>
        <Book-Comp></Book-Comp>
        <Book-Comp></Book-Comp>
        <Book-Comp></Book-Comp>
        <Book-Comp></Book-Comp>
      </section>
    </main>
</template>
